name: Deploy calendar app
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'packages/fetcher/**'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy calendar app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: yarn install
      - run: yarn build
      - name: Deploy
        run: flyctl deploy --remote-only --no-cache --config apps/calendar/fly.toml
