name: Update data
on:
  schedule:
    # 4時間ごと
    - cron: '0 */4 * * *'
  workflow_dispatch:
env:
  EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
  GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

jobs:
  fetch-data:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run fetcher
        run: yarn data:fetch
      - name: git setting
        run: |
          git config --local user.email ${EMAIL_ADDRESS}
          git config --local user.name ${GIT_USER_NAME}
      - id: diff
        run: echo "::set-output name=changed::$(git diff --name-only origin/main --relative packages/data | wc -l)"
      - if: ${{ steps.diff.outputs.changed != '0' }}
        name: git push
        run: |
          git add packages/data/data.json
          git commit -m "Update data" -a
          git push origin main
